Tests run by: Tnmk
Tests run at: 2023-02-03_22-45-19
Test suite: 
<unittest.suite.TestSuite tests=[<tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_add_location>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_add_location_to_occ_csv>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_add_url_to_json>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_check_location_exists>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_check_url>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_get_dict_from_url>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_get_lat_lon_from_url>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_get_response_from_url>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_remove_location>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_remove_location_from_csv>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_remove_location_from_json>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_update_characteristics_in_csv>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_update_location_occupancy>, <tests.utility.test_data_functions.Data_Functions_Tester testMethod=test_update_url_in_json>]>

Test results:
.......F......
======================================================================
FAIL: test_get_response_from_url (tests.utility.test_data_functions.Data_Functions_Tester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "S:\Dashboard\tests\utility\test_data_functions.py", line 150, in test_get_response_from_url
    self.assertRaises(Exception, get_response_from_url, "https://www.google.com")
AssertionError: Exception not raised by get_response_from_url

----------------------------------------------------------------------
Ran 14 tests in 0.141s

FAILED (failures=1)
